# Generated by Django 5.1 on 2024-08-26 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_registered',
        ),
        migrations.AddField(
            model_name='job',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='average_package',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
