# Generated by Django 5.1 on 2024-08-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_remove_job_is_registered_and_more'),
    ]

    operations = [
    ]
