# Generated by Django 5.1 on 2024-08-27 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_relatedmodel_remove_job_registered_users_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedModel',
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
              field=models.ForeignKey(to='jobs.CustomUser', on_delete=models.CASCADE, related_name='jobs_created'),
        ),
    ]
